#!/usr/bin/env python3
"""Generate docs/preview/icons.js — the data behind the preview page's icon-theme
showcase tabs.

Reads icon name mappings from iconography/icon_map.json, fetches the
corresponding Papirus SVGs, recolours them with the Osiris palette (via
scripts/lib/gen_icons.py), and embeds the inner SVG markup so the preview
page can render the icons without external files.

Two shipped icon themes:
  * file — VS Code "Osiris File Icons"     (icon_map.json → vscode_file)
  * xdg  — freedesktop icon theme "Osiris" (icon_map.json → xdg)

The product icon theme has been removed.

Run by `scripts/build.sh pages`; the output is committed so
docs/preview/index.html also works opened straight from disk.
"""
from __future__ import annotations

import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "preview" / "icons.js"
sys.path.insert(0, str(ROOT / "scripts" / "lib"))


def load(*parts: str) -> dict:
    return json.loads(ROOT.joinpath(*parts).read_text(encoding="utf-8"))


XDG_CATEGORY_CS = {
    "actions": "Akce", "apps": "Aplikace", "categories": "Kategorie nabídky",
    "devices": "Zařízení", "emblems": "Emblémy", "mimetypes": "Typy souborů",
    "places": "Místa", "status": "Stav",
}


def extract_inner_svg(svg_text: str) -> str:
    """Extract the inner XML of an SVG (everything between <svg ...> and </svg>)."""
    start = svg_text.find(">", svg_text.find("<svg"))
    end = svg_text.rfind("</svg>")
    if start == -1 or end == -1:
        return ""
    return svg_text[start + 1:end].strip()


def main() -> None:
    import gen_icons

    m = load("iconography", "icon_map.json")

    build_dir = os.environ.get("OSIRIS_BUILD_DIR",
                               str(ROOT / "build"))
    papirus_src = os.environ.get("OSIRIS_PAPIRUS_SRC",
                                 os.path.join(build_dir, "papirus-src"))
    gen_icons.ensure_papirus(papirus_src)
    papirus_root = os.path.join(papirus_src, "Papirus")

    def recolor_to_inner(cat: str, name: str) -> str:
        svg = gen_icons.read_papirus_svg(papirus_root, cat, name)
        if svg is None:
            return ""
        return extract_inner_svg(gen_icons.recolor_svg(svg))

    # ---- 1. VS Code file icons -------------------------------------------
    ft = m["vscode_file"]

    folders = []
    for label, name in [("folder", ft["folder"]), ("folder (otevřená)", ft["folderOpen"])]:
        inner = recolor_to_inner("places", name)
        if inner:
            folders.append({"svg": inner, "label": label})

    seen_folder = set()
    for fname, papirus_name in ft["folderNames"].items():
        if papirus_name in seen_folder:
            continue
        seen_folder.add(papirus_name)
        inner = recolor_to_inner("places", papirus_name)
        if inner:
            folders.append({"svg": inner, "label": papirus_name})

    def file_entries(section: dict) -> list:
        out = []
        for name, papirus_name in section.items():
            inner = recolor_to_inner("mimetypes", papirus_name)
            if inner:
                out.append({"svg": inner, "label": name})
        return out

    file_theme = {
        "id": "file",
        "name": "Osiris File Icons",
        "target": "VS Code · motiv ikon souborů",
        "note": "Papirus mimetype SVG přebarvená paletou Osiris. Sdílené s XDG "
                "ikonami souborů pro GNOME.",
        "groups": [
            {"title": f"Složky ({len(folders)})", "items": folders},
            {"title": f"Podle přípony ({len(ft['fileExtensions'])})",
             "items": file_entries(ft["fileExtensions"])},
            {"title": f"Podle názvu ({len(ft['fileNames'])})",
             "items": file_entries(ft["fileNames"])},
        ],
    }

    # ---- 2. XDG / freedesktop icon theme ------------------------------
    xdg_map = m.get("xdg", {})
    xdg_groups = []
    for cat, mapping in xdg_map.items():
        items = []
        seen = set()
        for xdg_name, papirus_name in mapping.items():
            if papirus_name in seen:
                continue
            seen.add(papirus_name)
            inner = recolor_to_inner(cat, papirus_name)
            if inner:
                items.append({"svg": inner, "label": xdg_name})
        if items:
            xdg_groups.append({
                "title": f"{XDG_CATEGORY_CS.get(cat, cat)} · {cat} ({len(items)})",
                "items": items,
            })

    xdg_theme = {
        "id": "xdg",
        "name": "Osiris",
        "target": "XDG / freedesktop · /usr/share/icons/Osiris (GNOME, KDE Plasma)",
        "note": "Papirus ikony přebarvené paletou Osiris. Dědí Papirus-Dark, "
                "Papirus, breeze, gnome, hicolor pro cokoli nestylované.",
        "groups": xdg_groups,
    }

    data = {
        "themes": [file_theme, xdg_theme],
    }

    banner = ("/* GENERATED by scripts/lib/gen_preview_icons.py from Papirus + "
              "iconography/icon_map.json — do not edit. */\n")
    OUT.write_text(
        banner + "window.OSIRIS_PREVIEW_ICONS = "
        + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    total = sum(len(gr["items"]) for th in data["themes"] for gr in th["groups"])
    print(f"gen_preview_icons: {len(data['themes'])} themes, {total} icon cards -> "
          f"{OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
