#!/usr/bin/env python3
"""Generate docs/preview/icons.js — the data behind the preview page's
"Aplikační ikony" / "Ikony souborů" tabs.

Single source of truth, like everything else: the glyph paths come from
iconography/glyphs.json, the wiring from iconography/map/{filetypes,xdg}.json and
the colours from assets/tokens.json (icon.fileIcon.palette / icon.xdg).

Run by `scripts/build.sh pages` (and `make icons`); the output is committed so
`docs/preview/index.html` also works when opened straight from disk.
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "preview" / "icons.js"


def load(*parts: str) -> dict:
    return json.loads((ROOT.joinpath(*parts)).read_text(encoding="utf-8"))


# --- friendly Czech labels for the deduped app / category glyphs -----------
APP_LABELS = {
    "text-editor": "Textový editor",
    "terminal-app": "Terminál",
    "file-manager": "Správce souborů",
    "web-browser": "Webový prohlížeč",
    "code": "Vývojové prostředí",
    "development": "Vývoj",
    "calculator": "Kalkulačka",
    "image-viewer": "Prohlížeč obrázků",
    "media-player": "Přehrávač videa",
    "music": "Přehrávač hudby",
    "mail": "Pošta",
    "help": "Nápověda",
    "package": "Software",
    "monitor": "Sledování systému",
    "settings": "Nastavení",
    "screenshot": "Snímek obrazovky",
    "color-picker": "Kapátko barev",
    "file-archive": "Správce archivů",
    "calendar": "Kalendář",
    "clock": "Hodiny",
}
CATEGORY_LABELS = {
    "development": "Vývoj",
    "graphics": "Grafika",
    "internet": "Internet",
    "multimedia": "Multimédia",
    "music": "Zvuk",
    "videos": "Video",
    "office": "Kancelář",
    "games": "Hry",
    "system": "Systém",
    "utilities": "Nástroje",
    "accessories": "Příslušenství",
    "science": "Věda",
    "education": "Vzdělávání",
    "package": "Ostatní",
    "preferences": "Předvolby",
    "settings": "Předvolby systému",
    "help": "Nápověda",
}


def main() -> None:
    glyphs = load("iconography", "glyphs.json")["glyphs"]
    ft = load("iconography", "map", "filetypes.json")
    xdg = load("iconography", "map", "xdg.json")["icons"]
    tok = load("assets", "tokens.json")["icon"]

    palette = tok["fileIcon"]["palette"]
    file_default = tok["fileIcon"]["default"]
    folder_tok = tok["fileIcon"]["folder"]
    folder_open_tok = tok["fileIcon"]["folderOpen"]
    apps_color = tok["xdg"]["categoryColor"]["apps"]
    cats_color = tok["xdg"]["categoryColor"]["categories"]

    def g(key: str) -> dict:
        gl = glyphs[key]
        return {"glyph": key, "d": gl["d"], "evenodd": bool(gl.get("evenodd"))}

    def color_of(name: str) -> str:
        return file_default if name == "default" else palette.get(name, file_default)

    # ---- file icons ------------------------------------------------------
    folders = [
        {**g("folder"), "label": "folder", "dark": folder_tok["dark"], "light": folder_tok["light"]},
        {**g("folder-open"), "label": "folder (otevřená)", "dark": folder_open_tok["dark"], "light": folder_open_tok["light"]},
    ]
    seen = set()
    for glyph in ft["folderNames"].values():
        if glyph in seen or glyph not in glyphs:
            continue
        seen.add(glyph)
        folders.append({**g(glyph), "label": glyph, "dark": folder_tok["dark"], "light": folder_tok["light"]})

    def file_entries(section: dict) -> list:
        out = []
        for name, spec in section.items():
            glyph = spec["glyph"]
            if glyph not in glyphs:
                continue
            out.append({**g(glyph), "label": name, "color": color_of(spec.get("color", "default"))})
        return out

    extensions = file_entries(ft["fileExtensions"])
    filenames = file_entries(ft["fileNames"])

    # ---- application icons --------------------------------------------
    def dedupe(mapping: dict, labels: dict, color: str) -> list:
        out, seen_g = [], set()
        for _key, glyph in mapping.items():
            if glyph in seen_g or glyph not in glyphs:
                continue
            seen_g.add(glyph)
            out.append({**g(glyph), "label": labels.get(glyph, glyph.replace("-", " ")), "color": color})
        return out

    apps = dedupe(xdg["apps"], APP_LABELS, apps_color)
    categories = dedupe(xdg["categories"], CATEGORY_LABELS, cats_color)

    data = {
        "file": {"folders": folders, "extensions": extensions, "filenames": filenames},
        "app": {"apps": apps, "categories": categories},
    }

    banner = (
        "/* GENERATED by scripts/lib/gen_preview_icons.py from iconography/ + "
        "assets/tokens.json — do not edit. */\n"
    )
    OUT.write_text(
        banner + "window.OSIRIS_PREVIEW_ICONS = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    n = len(extensions) + len(filenames) + len(folders) + len(apps) + len(categories)
    print(f"gen_preview_icons: {n} icons -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
